= Git Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:delta: https://dandavison.github.io/delta/[delta]
:Git: https://git-scm.org/[Git]
:pre-commit: https://pre-commit.com/[pre-commit]
:Sublime-Merge: https://www.sublimemerge.com/[Sublime Merge]
:Visual-Studio-Code: https://code.visualstudio.com/[Visual Studio Code]

My configuration for {Git}.

The configuration uses {Visual-Studio-Code} as the editor and {Sublime-Merge} as the merge tool.
{delta} is used to provide syntax highlighting on the command-line.

== Usage

This repository contains the configuration file for {Git}.
This file is synchronized using this Git repository.
The following instructions detail how to use this repository.

=== Install

Install these settings with the following instructions.
The instructions target a Fedora Atomic system.

. Install the `git-credential-libsecret`, `git-delta`, and `pre-commit` packages.
+
[,sh]
----
sudo rpm-ostree install git-credential-libsecret git-delta pre-commit
----

. Reboot to apply the changes.
+
[,sh]
----
sudo systemctl reboot
----

. Clone this repository.
+
[,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/git-config.git
----

. Copy the `work.inc.template` file to `work.inc`.
+
[,sh]
----
cp config/work.inc.template to config/work.inc
----

. Replace the example email with the work email account. 
All projects under the `~/Projects/Work` directory will use the Git configuration in this file.

. Symlink the configuration directory `config` to the `~/.config/git` directory.
+
[,sh]
----
ln --relative --symbolic --force ~/Projects/git-config/config ~/.config/git
----

== References

* https://wiki.archlinux.org/title/git#Using_git-credential-libsecret_as_credential-helper[Arch Linux Wiki: Git - Using git-credential-libsecret as credential-helper]
* https://github.com/dandavison/delta#get-started[delta - Getting Started]
* https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work[Git Book: 7.4 Git Tools - Signing Your Work]
* https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration[Git Book: 8.1 Customizing Git - Git Configuration]
* https://git-scm.com/docs/git-config[git-config]
* https://pre-commit.com/#automatically-enabling-pre-commit-on-repositories[pre-commit: automatically enabling pre-commit on repositories]
* https://www.sublimemerge.com/docs/command_line#Git-Merge-Tool-Setup[Sublime Merge Documentation - Command Line: Git Merge Tool Setup]
* https://code.visualstudio.com/docs/sourcecontrol/overview#_vs-code-as-git-difftool-and-mergetool[VS Code as Git difftool and mergetool]

== Code of Conduct

Please refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3].
Please refer to the bundled link:LICENSE.adoc[license].

The `config/template/hooks/pre-commit` file was generated by {pre-commit} using the following command.

[,sh]
----
pre-commit init-templatedir ~/.config/git/template
----

The `config/template/hooks/pre-commit` file is from https://pre-commit.com/#automatically-enabling-pre-commit-on-repositories[pre-commit: automatically enabling pre-commit on repositories].

== Copyright

© 2020-2024 Jordan Williams

== Authors

mailto:{email}[{author}]
