#!/usr/bin/bash
# Prompt the user to install pre-commit hooks when there is a .pre-commit-config-yaml file present in the repository.
# Code from https://pre-commit.com/#automatically-enabling-pre-commit-on-repositories.

if [ -f .pre-commit-config.yaml ]; then
    echo 'pre-commit configuration detected, but `pre-commit install` was never run' 1>&2
    exit 1
fi
